logging:
  level: INFO
  loggers:
    com.akhilesh.learning: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 9090
      useProxyProtocol: true
  adminConnectors:
    - type: http
      port: 9091
